services:
  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: db_legacyd_one
      MYSQL_USER: legacy_admin
      MYSQL_PASSWORD: P@ssw0rd2025
      MYSQL_ROOT_PASSWORD: P@ssw0rd2025
    ports:
      - "3307:3306"  # Changed from 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
  redis:
    image: redis:latest
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
volumes:
  dbdata: